# Generated by Django 3.2.4 on 2022-06-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('userimage', models.ImageField(upload_to='')),
                ('userimgname', models.CharField(max_length=500)),
            ],
        ),
    ]
